server:
  #shiro timeout ms
  session-timeout: 3600000
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  port: 80
  contextPath: /oms
security:
  basic:
    enabled: false
web:
  #文件上传配置 must end with '/'
  #upload-path: C:/upload/
  #upload-path: E:/upload/
  upload-path: /home/hu/upload/
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    #在这里配置需要加载哪个配置文件
    active: dev
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
#  favicon:
#      enabled: true
mybatis-plus:
  mapper-locations: mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hu.**.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
hu:
  default-password: 123456
  charset: UTF-8
  company-name: 小小测试
  mail:
    suffix: china-hu.com
    generate-mode:  1 #邮箱生成格式  1.全拼  2.姓全拼+名首字母
    smtp-server:  smtp.163.com
    account: test231321@163.com
    password: 123456
